<script setup>
import { defineProps } from "vue";

import { useStore } from "vuex";

const store = useStore();

const props = defineProps({
  title: {
    type: String,
    default: "ppepepepepepepepepepepepep",
  },
});
</script>

<template>
  <header :class="`${store.state.is_expanded ? 'is-expanded' : ''}`">
    <nav>
      <h1>{{ props.title }}</h1>
      <h2>{{ store.state.is_expanded }}</h2>
      LENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLE
    </nav>
  </header>
</template>

<style lang="scss" scoped>
header {
  width: calc(100vw - (2rem + 32px));
  padding: 2rem;

  * {
    max-width: 99%;
    overflow: hidden;
  }

  &.is-expanded {
    width: calc(100vw - var(--sidebar-width));
  }
}
</style>
