<script setup>
import { defineProps } from "vue";

const props = defineProps({
  title: {
    type: String,
    default: "ppepepepepepepepepepepepep",
  },
});
</script>

<template>
  <header>
    <nav>
      <h1>{{ props.title }}</h1>
      LENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLELENLENLENLE
    </nav>
  </header>
</template>

<style lang="scss" scoped>
nav {
  padding: 2rem;
  max-width: calc(100vw - var(--sidebar-width));
  overflow: hidden;
}
</style>
