CREATE TABLE [User]
(
	Id UNIQUEIDENTIFIER NOT NULL,
	Username NVARCHAR(255) NOT NULL, 
	PasswordHash VARBINARY NOT NULL,
	PasswordSalt VARBINARY NOT NULL
)

GO

ALTER TABLE [User]
ADD CONSTRAINT PK_User PRIMARY KEY(Id)

GO

ALTER TABLE [User]
ADD CONSTRAINT DF_Id DEFAULT NEWID() FOR Id